spring.datasource.url=jdbc:postgresql://localhost:5432/teams_db
spring.datasource.username=postgres
spring.datasource.password=BDGJ
jwt.secret=techcup-clave-secreta-minimo-256-bits-cambiar-en-produccion
jwt.expiration=86400000
tournament-service.url=http://localhost:8084